server:
  port: ${discord.server.port}
spring:
  profiles:
    #?????
    active: test
  application:
    name: rookie_discord_api
  datasource:
    url: jdbc:mysql://${discord.mysql.ip}:${discord.mysql.port}/${discord.mysql.db}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ${discord.mysql.username}
    password: ${discord.mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  mail:
    host: ${discord.mail.host} # 邮件服务地址
    username: ${discord.mail.username}
    password: ${discord.mail.password}
    default-encoding: UTF-8 # 默认的邮件编码为UTF-8
    properties:
      mail:
        smtp:
          auth: true
          # 如果是用 SSL 方式，需要配置如下属性,使用qq邮箱的话需要开启
          starttls:
            enable: true
            required: true

# logger ??
logging:
  config: classpath:logback.xml

#mybatis-plus????????????SQL??
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-handlers-package:
    com.rookie.stack.discord.common.handler